service: hostel-issue-tracker

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 10
  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    WARDEN_SECRET_KEY: ${env:WARDEN_SECRET_KEY}
    AWS_S3_BUCKET_NAME: ${env:AWS_S3_BUCKET_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${env:AWS_S3_BUCKET_NAME}/*"

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
